apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: whatever
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug-v0.16.0
    imagePullPolicy: Always
    command:
    - cat
    tty: true
    resources:
      requests:
        memory: "6Gi"
      limits:
        memory: "8Gi"
    volumeMounts:
    - name: kaniko
      mountPath: /kaniko/.docker/
  volumes:
  - name: kaniko
    emptyDir: {}
